@AppointmentAPI_HostAddress = http://localhost:5087
@token = CopiedToken

# GET {{AppointmentAPI_HostAddress}}/weatherforecast/
# Accept: application/json

###


POST {{AppointmentAPI_HostAddress}}/api/Auth/register
Content-Type: application/json

{
  "userName": "sifatsakib26",
  "password": "123456"
}

### 

POST {{AppointmentAPI_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "username": "sifatsakib26",
  "password": "123456"
}


###

GET {{AppointmentAPI_HostAddress}}/api/Appointment/check-auth
Authorization: Bearer {{token}}


### Create an Appointment


POST {{AppointmentAPI_HostAddress}}/api/Appointment
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "patientName": "Sifat Sakib sssss",
  "patentContact": "abir@example.com",
  "appointmentDateTime": "2025-07-02T10:30:00",
  "doctorId": 2
}


### Get All Appointments
GET {{AppointmentAPI_HostAddress}}/api/Appointment
Authorization: Bearer {{token}}


### Get Appointment by ID
GET {{AppointmentAPI_HostAddress}}/api/Appointment/2
Authorization: Bearer {{token}}


### Update an Appointment
PUT {{AppointmentAPI_HostAddress}}/api/Appointment/1
/Authorization: Bearer {{token}}
Content-Type: application/json

{
  "patientName": "Talha",
  "patentContact": "jane@example.com",
  "appointmentDateTime": "2025-02-05T15:00:00",
  "doctorId": 2
}

### Delete an Appointment
DELETE {{AppointmentAPI_HostAddress}}/api/Appointment/3
Authorization: Bearer {{token}}